### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AllanLRH** [mottosso/PersistentPython#3]
It doesn't work on my machine (mac 10.10, ST 3125), and seems to take other plugins with it as well, including Package Control.

Console shows this error during startup:
```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 191, in create_window_commands
    cmds.append(class_(window))
  File "persistent_python in /Users/allan/Library/Application Support/Sublime Text 3/Installed Packages/PersistentPython.sublime-package", line 19, in __init__
NotADirectoryError: [Errno 20] Not a directory: '/Users/allan/Library/Application Support/Sublime Text 3/Installed Packages/PersistentPython.sublime-package/Persistent Python.sublime-build'
```

**Comment by Kristinita** [comment]
@mottosso , I reproduce the problem in 

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Package Control doesn't work after PersistentPython installation.

Thanks.

**Comment by mottosso** [comment]
Hi, apologies for the very late reply. You are right, this doesn't work, the plug-in never got finished. Sorry for the trouble, I've disabled it for now, pending permanent deletion.

Thanks for letting me know!

**Comment by ric2b** [comment]
Any plans to finish it? Any help needed?

**Comment by mottosso** [comment]
@ric2b I've got some ideas on how to better approach it, but no timeline in which to implement it.

The idea would be to (1) upon launch of Sublime, start an external Python interpreter via subprocess and (2) send the contents of a Sublime document via `Popen.stdin` and (3) read results from `Popen.stdout` back into the Sublime console window.

That way, you wouldn't have to save your file in order to run it, and each run would be made within the same interpreter session as the last, much like it would in embedded sessions such as Autodesk Maya and Foundry Nuke.

At various points, it would make sense to reset the interpreter, in which case a new Python process could be started, replacing the first one.

What do you think?

**Comment by ric2b** [comment]
@mottosso Makes sense to me. I have no experience with Sublime plugins though.
What issues were you running into, did you figure that out?

**Comment by BejaouiSayf** [comment]
I have the same problems (package control lost and the persistent python is not working).
